/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OAuth struct {
	Url string `json:"url"`
	ClientId string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}
