/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Events struct {
	// AsynApi file v1: https://github.com/asyncapi/asyncapi/blob/develop/schema/asyncapi.json
	Spec *interface{} `json:"spec,omitempty"`
}
