/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Api struct {
	TargetUrl string `json:"targetUrl"`
	Credentials *ApiCredentials `json:"credentials,omitempty"`
	// OpenApi v2 swagger file: https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json
	Spec *interface{} `json:"spec,omitempty"`
}
