/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ApiErrorDetail - schema for specific error detail
type ApiErrorDetail struct {

	// a bean notation expression specifying the element in request data causing the error, eg product.variants[3].name, this can be empty if violation was not field specific
	Field string `json:"field,omitempty"`

	// classification of the error detail type, lower case with underscore eg missing_value, this value must be always interpreted in context of the general error type.
	Type string `json:"type"`

	// descriptive error detail message for debugging
	Message string `json:"message,omitempty"`

	// link to documentation to investigate further and finding support for error detail
	MoreInfo string `json:"moreInfo,omitempty"`
}
