/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServiceDetails struct {

	Provider string `json:"provider"`

	Name string `json:"name"`

	Description string `json:"description"`

	Api *Api `json:"api,omitempty"`

	Events *Events `json:"events,omitempty"`

	Documentation *Documentation `json:"documentation,omitempty"`
}
