/*
 * Kyma Gateway Metadata API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Documentation struct {

	DisplayName string `json:"displayName"`

	Description string `json:"description"`

	Type string `json:"type"`

	Tags []string `json:"tags,omitempty"`

	Docs []Document `json:"docs,omitempty"`
}
